import {CapacitorSQLite,SQLiteConnection,SQLiteDBConnection} from '@capacitor-community/sqlite';
import {Capacitor} from '@capacitor/core';
import {addFrequency,isoToday} from '../utils/ethiopianCalendar';
export type Frequency='2w'|'1m'|'2m'|'3m';
export interface Client{id:number;name:string;phone:string;status:'new'|'returning';frequency:Frequency;lastVisitDate:string;nextExpectedDate:string;createdAt:string;updatedAt:string;totalVisits?:number;totalSpent?:number}
export interface Visit{id:number;clientId:number;visitNumber:number;date:string;service:string;amountPaid:number;paymentMethod:string;notes:string;createdAt:string;updatedAt:string}
export interface Income{id:number;date:string;type:'client_visit'|'other';clientId:number|null;visitId:number|null;description:string;amount:number;createdAt:string}
const DB='sara_salon.db';const sqlite=new SQLiteConnection(CapacitorSQLite);let conn:SQLiteDBConnection|null=null;let ready:Promise<void>|null=null;
async function persist(){if(Capacitor.getPlatform()==='web')await sqlite.saveToStore(DB)}
async function init(){if(Capacitor.getPlatform()==='web'){const el=document.createElement('jeep-sqlite');document.body.appendChild(el);await customElements.whenDefined('jeep-sqlite');await sqlite.initWebStore()}const c=await sqlite.checkConnectionsConsistency();const exists=(await sqlite.isConnection(DB,false)).result;conn=(c.result&&exists)?await sqlite.retrieveConnection(DB,false):await sqlite.createConnection(DB,false,'no-encryption',1,false);await conn.open();await conn.execute(`CREATE TABLE IF NOT EXISTS clients(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT NOT NULL,status TEXT NOT NULL,frequency TEXT NOT NULL,lastVisitDate TEXT NOT NULL,nextExpectedDate TEXT NOT NULL,createdAt TEXT NOT NULL,updatedAt TEXT NOT NULL);CREATE TABLE IF NOT EXISTS visits(id INTEGER PRIMARY KEY AUTOINCREMENT,clientId INTEGER NOT NULL,visitNumber INTEGER NOT NULL,date TEXT NOT NULL,service TEXT NOT NULL,amountPaid REAL NOT NULL,paymentMethod TEXT NOT NULL,notes TEXT NOT NULL,createdAt TEXT NOT NULL,updatedAt TEXT NOT NULL,FOREIGN KEY(clientId) REFERENCES clients(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS income(id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT NOT NULL,type TEXT NOT NULL,clientId INTEGER,visitId INTEGER UNIQUE,description TEXT NOT NULL,amount REAL NOT NULL,createdAt TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_clients_next ON clients(nextExpectedDate);CREATE INDEX IF NOT EXISTS idx_visits_client ON visits(clientId);CREATE INDEX IF NOT EXISTS idx_income_date ON income(date);`);await persist()}
export function initDb(){return ready??(ready=init())} function db(){if(!conn)throw Error('Database not initialized');return conn}
export async function allClients(){await initDb();return (await db().query('SELECT c.*,COALESCE((SELECT COUNT(*) FROM visits v WHERE v.clientId=c.id),0) totalVisits,COALESCE((SELECT SUM(amountPaid) FROM visits v WHERE v.clientId=c.id),0) totalSpent FROM clients c ORDER BY c.name COLLATE NOCASE')).values as Client[]||[]}
export async function getClient(id:number){await initDb();return ((await db().query('SELECT * FROM clients WHERE id=?',[id])).values as Client[]||[])[0]}
export async function visitsForClient(id:number){await initDb();return (await db().query('SELECT * FROM visits WHERE clientId=? ORDER BY date DESC,id DESC',[id])).values as Visit[]||[]}
export async function visitsOn(date:string){await initDb();return (await db().query('SELECT v.*,c.name,c.phone FROM visits v JOIN clients c ON c.id=v.clientId WHERE v.date=? ORDER BY v.id DESC',[date])).values||[]}
export async function clientsDue(date:string){await initDb();return (await db().query('SELECT * FROM clients WHERE nextExpectedDate=? ORDER BY name COLLATE NOCASE',[date])).values as Client[]||[]}
export async function addClient(input:{name:string;phone:string;service:string;amount:number;frequency:Frequency;date:string;paymentMethod:string}){await initDb();const now=new Date().toISOString();const next=addFrequency(input.date,input.frequency);const r=await db().run('INSERT INTO clients(name,phone,status,frequency,lastVisitDate,nextExpectedDate,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?)',[input.name,input.phone,'new',input.frequency,input.date,next,now,now]);const id=r.changes?.lastId??-1;const vr=await db().run('INSERT INTO visits(clientId,visitNumber,date,service,amountPaid,paymentMethod,notes,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?)',[id,1,input.date,input.service,input.amount,input.paymentMethod,'',now,now]);const visitId=vr.changes?.lastId??-1;await db().run('INSERT INTO income(date,type,clientId,visitId,description,amount,createdAt) VALUES(?,?,?,?,?,?,?)',[input.date,'client_visit',id,visitId,input.service,input.amount,now]);await persist();return id}
export async function completeVisit(clientId:number,input:{date:string;service:string;amount:number;paymentMethod:string;notes:string}){await initDb();const c=await getClient(clientId);if(!c)throw Error('Client not found');const count=((await db().query('SELECT COUNT(*) n FROM visits WHERE clientId=?',[clientId])).values?.[0] as any)?.n||0;const now=new Date().toISOString();const n=count+1;const vr=await db().run('INSERT INTO visits(clientId,visitNumber,date,service,amountPaid,paymentMethod,notes,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?)',[clientId,n,input.date,input.service,input.amount,input.paymentMethod,input.notes||'',now,now]);const visitId=vr.changes?.lastId??-1;await db().run('INSERT INTO income(date,type,clientId,visitId,description,amount,createdAt) VALUES(?,?,?,?,?,?,?)',[input.date,'client_visit',clientId,visitId,input.service,input.amount,now]);await db().run('UPDATE clients SET status=?,lastVisitDate=?,nextExpectedDate=?,updatedAt=? WHERE id=?',['returning',input.date,addFrequency(input.date,c.frequency),now,clientId]);await persist()}
export async function addOtherIncome(date:string,description:string,amount:number){await initDb();await db().run('INSERT INTO income(date,type,clientId,visitId,description,amount,createdAt) VALUES(?,?,?,?,?,?,?)',[date,'other',null,null,description,amount,new Date().toISOString()]);await persist()}
export async function incomeFor(dateFrom?:string,dateTo?:string){await initDb();if(dateFrom&&dateTo)return (await db().query('SELECT * FROM income WHERE date BETWEEN ? AND ? ORDER BY date DESC,id DESC',[dateFrom,dateTo])).values as Income[]||[];return (await db().query('SELECT * FROM income ORDER BY date DESC,id DESC')).values as Income[]||[]}
export async function deleteClient(id:number){await initDb();await db().run('DELETE FROM income WHERE clientId=?',[id]);await db().run('DELETE FROM visits WHERE clientId=?',[id]);await db().run('DELETE FROM clients WHERE id=?',[id]);await persist()}
export async function dailyIncome(date:string){await initDb();return Number(((await db().query('SELECT COALESCE(SUM(amount),0) n FROM income WHERE date=?',[date])).values?.[0] as any)?.n||0)}
export async function stats(){await initDb();const clients=((await db().query('SELECT COUNT(*) n FROM clients')).values?.[0] as any)?.n||0;const visits=((await db().query('SELECT COUNT(*) n FROM visits')).values?.[0] as any)?.n||0;const spent=((await db().query('SELECT COALESCE(SUM(amountPaid),0) n FROM visits')).values?.[0] as any)?.n||0;return{clients,visits,spent}}
